---
- name: 'Downloading wordpress 4.9.5 package'
  get_url:
    url: 'https://wordpress.org/wordpress-4.9.5.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Unarchive wordpress package'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: 'Copy wordpress config file'
  copy:
    src: "{{ wp_install_dir }}/wp-config-sample.php"
    dest: "{{ wp_install_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Replace database configs'
  replace:
    path: "{{ wp_install_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_username }}" }
    - { regex: 'password_here', value: "{{ wp_userpassword }}" }
    - { regex: 'localhost', value: "{{ wp_db_ip }}" }
  become: yes

- name: 'Update apache config for wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache
