---
- name: 'Install dependencies'
  apt:
    name: ['mysql-server-5.6', 'python-mysqldb']
    state: latest
  become: yes

- name: 'Setup Database'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present

- name: 'Creating database user'
  mysql_user:
    name: "{{wp_username}}"
    login_user: root
    password: "{{ wp_userpassword }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - "{{ wp_host_ip }}"

- name: 'Copy mysql configuration'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify: restart mysql
